/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleCharactersIndexRouteImport } from './routes/$locale/characters/index'
import { Route as LocaleCharactersIdRouteImport } from './routes/$locale/characters/$id'
import { Route as LocaleFruitsIndexRouteImport } from './routes/$locale/fruits/index'
import { Route as LocaleFruitsIdRouteImport } from './routes/$locale/fruits/$id'
import { Route as LocalePlacesIndexRouteImport } from './routes/$locale/places/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCharactersIndexRoute = LocaleCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCharactersIdRoute = LocaleCharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFruitsIndexRoute = LocaleFruitsIndexRouteImport.update({
  id: '/fruits/',
  path: '/fruits/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFruitsIdRoute = LocaleFruitsIdRouteImport.update({
  id: '/fruits/$id',
  path: '/fruits/$id',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePlacesIndexRoute = LocalePlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/characters/$id': typeof LocaleCharactersIdRoute
  '/$locale/fruits/$id': typeof LocaleFruitsIdRoute
  '/$locale/characters/': typeof LocaleCharactersIndexRoute
  '/$locale/fruits/': typeof LocaleFruitsIndexRoute
  '/$locale/places/': typeof LocalePlacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/characters/$id': typeof LocaleCharactersIdRoute
  '/$locale/fruits/$id': typeof LocaleFruitsIdRoute
  '/$locale/characters': typeof LocaleCharactersIndexRoute
  '/$locale/fruits': typeof LocaleFruitsIndexRoute
  '/$locale/places': typeof LocalePlacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/characters/$id': typeof LocaleCharactersIdRoute
  '/$locale/fruits/$id': typeof LocaleFruitsIdRoute
  '/$locale/characters/': typeof LocaleCharactersIndexRoute
  '/$locale/fruits/': typeof LocaleFruitsIndexRoute
  '/$locale/places/': typeof LocalePlacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/$locale/characters/$id'
    | '/$locale/fruits/$id'
    | '/$locale/characters/'
    | '/$locale/fruits/'
    | '/$locale/places/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/characters/$id'
    | '/$locale/fruits/$id'
    | '/$locale/characters'
    | '/$locale/fruits'
    | '/$locale/places'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/$locale/characters/$id'
    | '/$locale/fruits/$id'
    | '/$locale/characters/'
    | '/$locale/fruits/'
    | '/$locale/places/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/characters/': {
      id: '/$locale/characters/'
      path: '/characters'
      fullPath: '/$locale/characters/'
      preLoaderRoute: typeof LocaleCharactersIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/characters/$id': {
      id: '/$locale/characters/$id'
      path: '/characters/$id'
      fullPath: '/$locale/characters/$id'
      preLoaderRoute: typeof LocaleCharactersIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/fruits/': {
      id: '/$locale/fruits/'
      path: '/fruits'
      fullPath: '/$locale/fruits/'
      preLoaderRoute: typeof LocaleFruitsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/fruits/$id': {
      id: '/$locale/fruits/$id'
      path: '/fruits/$id'
      fullPath: '/$locale/fruits/$id'
      preLoaderRoute: typeof LocaleFruitsIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/places/': {
      id: '/$locale/places/'
      path: '/places'
      fullPath: '/$locale/places/'
      preLoaderRoute: typeof LocalePlacesIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleCharactersIdRoute: typeof LocaleCharactersIdRoute
  LocaleFruitsIdRoute: typeof LocaleFruitsIdRoute
  LocaleCharactersIndexRoute: typeof LocaleCharactersIndexRoute
  LocaleFruitsIndexRoute: typeof LocaleFruitsIndexRoute
  LocalePlacesIndexRoute: typeof LocalePlacesIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleCharactersIdRoute: LocaleCharactersIdRoute,
  LocaleFruitsIdRoute: LocaleFruitsIdRoute,
  LocaleCharactersIndexRoute: LocaleCharactersIndexRoute,
  LocaleFruitsIndexRoute: LocaleFruitsIndexRoute,
  LocalePlacesIndexRoute: LocalePlacesIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
